name: Maven Build and Snapshot Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check that version is a SNAPSHOT
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "Detected version: $VERSION"
          if [[ "$VERSION" != *-SNAPSHOT ]]; then
            echo "❌ Version is not a SNAPSHOT. Aborting GitHub Packages deploy."
            exit 1
          fi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          cache: 'maven'

      - name: Build and Deploy SNAPSHOT to GitHub Packages
        run: mvn clean deploy --no-transfer-progress --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}