name: Publish package to the Maven Central Repository and GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: maven
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.OSSRH_USERNAME  }}
          server-password: ${{ secrets.OSSRH_TOKEN  }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Increment Version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          git config user.name GitHubActions
          git config user.email githubactions@github.com
          git add pom.xml
          git commit -m "updated version in pom.xml"
          git push
      - name: Create Git Tag
        run: |
          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout')
          git config user.name GitHubActions
          git config user.email githubactions@github.com
          git tag -a $version -m "$version"
          git push origin $version
      - name: Publish to the Maven Central Repository
        run: mvn --no-transfer-progress --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}


