name: Publish package to the Maven Central Repository and GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GPG_PRIVATE_KEY_ID }}
          gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@github.com"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Publish to the Maven Central Repository
        run: mvn --no-transfer-progress --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}




