name: Publish package to the Maven Central Repository and GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: MAVEN_GPG_PRIVATE_KEY
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Deploy with Maven
        run: mvn --no-transfer-progress deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          #MAVEN_USERNAME: maven_username123
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}