name: Publish to Maven Central
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #  with:
      #    fetch-depth: 0  # Ensures all tags are fetched for versioning
      - name: Set up JDK 21 and GPG for Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: Build and deploy to Maven Central
        run: mvn clean deploy -PsonatypeDeploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} --batch-mode --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }} secrets.GPG_PASSPHRASE }}