name: Check Sonatype Authentication

on:
  workflow_dispatch:

jobs:
  auth-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check OSSRH credentials with curl
        run: |
          echo "Checking authentication to Sonatype..."
          STATUS=$(curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" -s -o /dev/null -w "%{http_code}" \
            https://s01.oss.sonatype.org/service/local/status)
          
          if [ "$STATUS" -eq 200 ]; then
            echo "✅ Authentication successful: HTTP $STATUS"
          else
            echo "❌ Authentication failed: HTTP $STATUS"
            exit 1
          fi
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}